development:
  adapter: postgresql
  database: search_word_creator
  host: localhost
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: search_word_creator_test
  host: localhost
  pool: 5
  timeout: 5000

cucumber:
  <<: *test